-- Create requests table for user requests
create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null check (type in ('artist', 'song', 'other')),
  artist_name text,
  song_title text,
  url text,
  comment text,
  status text not null default 'pending'
);

-- Create index for faster queries
create index if not exists requests_type_idx on public.requests (type);
create index if not exists requests_status_idx on public.requests (status);
create index if not exists requests_created_at_idx on public.requests (created_at desc);

-- Add comment to table
comment on table public.requests is 'ユーザーからのリクエスト（アーティスト追加、楽曲追加、その他）を保存するテーブル';
